apiVersion: batch/v1
kind: Job
metadata:
  name: anagrams-job
spec:
  template:
    spec:
      containers:
        -
          image: vivianemaker1/santander-anagrams:latest
          name: anagrams-container
          volumeMounts:
            -
              mountPath: /data
              name: anagrams-volume
              readOnly: true
      initContainers:
        -
          args: []
          command:
            - sh
            - '-c'
            - 'set -x ; cd /data ; wget ${URL}'
          env:
            -
              name: URL
              value: https://raw.githubusercontent.com/Viviane-maker/santander-anagrams/docker/data/words.txt
          image: busybox
          name: anagrams-wget
          volumeMounts:
            -
              mountPath: /data
              name: anagrams-volume
              readOnly: false
      restartPolicy: Never
      volumes:
        -
          name: anagrams-volume
          persistentVolumeClaim:
            claimName: anagrams-pvc
            readOnly: false
          
