apiVersion: batch/v1
kind: Job
metadata:
  name: anagrams-job
spec:
  template:
    spec:
      containers:
        -
          image: vivianemaker1/santander-anagrams:latest
          name: anagrams-container
          volumeMounts:
            -
              mountPath: /data
              name: anagrams-volume
              readOnly: true
      imagePullSecrets:
        -
          name: docker-login
      initContainers:
        -
          args: []
          command:
            - sh
            - '-c'
            - 'set -x ; cd /downloads ; wget -r ${URL}'
          env:
            -
              name: URL
              valueFrom:
                secretKeyRef:
                  key: URL
                  name: anagrams-secret
          image: busybox
          name: anagrams-wget
          volumeMounts:
            -
              mountPath: /downloads
              name: anagrams-volume
              readOnly: false
      restartPolicy: Never
      volumes:
        -
          name: anagrams-volume
          persistentVolumeClaim:
            claimName: anagrams-pvc
            readOnly: false
          
